use_frameworks!

target 'TartuWeatherProvider_Example' do
  pod 'TartuWeatherProvider', :path => '../'

  target 'TartuWeatherProvider_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
