osx_image: xcode8.2
language: objective-c
before_install:
  - pod repo update --silent
  - gem install cocoapods
  - pod install --project-directory=Example
  - instruments -s devices
  - xcodebuild -showsdks
script:
- set -o pipefail && xcodebuild -workspace Example/TartuWeatherProvider.xcworkspace -scheme TartuWeatherProvider_Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean test build | xcpretty
- pod lib lint --verbose