osx_image: xcode10.2
language: objective-c
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage update
  - brew outdated swiftlint || brew upgrade swiftlint
  - gem install cocoapods --pre
  - gem cleanup
script:
- ./build.sh
- swift build
- pod repo update
- pod lib lint --verbose
