osx_image: xcode11.1
language: objective-c
before_install:
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint
  - gem install cocoapods
  - gem cleanup
script:
- ./build.sh
- swift build
- pod repo update
- pod lib lint --verbose
