osx_image: xcode9
language: objective-c
before_install:
  - gem install cocoapods
  - pod repo update --silent
  - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild -workspace Example/TartuWeatherProvider.xcworkspace -scheme TartuWeatherProvider_Example -destination 'platform=iOS Simulator,name=iPhone X' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean test build | xcpretty
- pod lib lint --verbose