version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.2.0"

    steps:
      - checkout

      - run:
          name: Set timezone
          command: sudo systemsetup -settimezone Europe/Tallinn

      - run:
          name: Carthage
          command: |
            brew update
            brew outdated carthage || brew upgrade carthage
            carthage update

      - run:
          name: Install Swiftlint
          command: brew install swiftlint

      - run:
          name: Update pods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            pod install --project-directory=Example

      - run:
          name: Test and build iOS
          command: set -o pipefail && xcodebuild -project TartuWeatherProvider.xcodeproj -scheme TartuWeatherProvider-iOS -destination 'platform=iOS Simulator,name=iPhone X' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean test build | xcpretty

      - run:
          name: Build other platforms
          command: |
            set -o pipefail && xcodebuild -project TartuWeatherProvider.xcodeproj -scheme TartuWeatherProvider-tvOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build | xcpretty
            set -o pipefail && xcodebuild -project TartuWeatherProvider.xcodeproj -scheme TartuWeatherProvider-watchOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build | xcpretty
            set -o pipefail && xcodebuild -project TartuWeatherProvider.xcodeproj -scheme TartuWeatherProvider-macOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build | xcpretty

      - run:
          name: Pod lib lint
          command: pod lib lint --allow-warnings

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
