update_fastlane

default_platform :ios

platform :ios do
  desc "Depoy new Tartu Weather provider version"
  lane :release do
    ensure_git_branch
    version = version_get_podspec(path: "TartuWeartherProvider.podspec")
    changelog = prompt(text: "Changelog: ", multi_line_end_keyword: "END")
    github_release = set_github_release(
      repository_name: "fassko/TartuWeatherProvider",
      api_token: ENV['GITHUB_TOKEN'],
      name: version,
      tag_name: version,
      description: changelog,
      commitish: "master"
    )
    sh("git fetch --tags")
    pod_push(allow_warnings: true, verbose: true)
  end

end